name = "Beyond the Horizon 2"
author = "BTH Team"
version = "0.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5b9c1f6ab2bea96aea541cf3e13aa19ce5ad359f8591d6a6cebd295b6fed1a9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
