name = "Beyond the Horizon 2"
author = "BTH Team"
version = "0.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c9d9970e9c57bbf01c96a02d75b08e052d42c8f8617a715781c7cb447b054a2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
