name = "Beyond the Horizon 2"
author = "BTH Team"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0ac7997d3ec35c12f939ab169e70b50fe2dc358d4d8443c4f7a76a4841da510"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
