declare module "betterdays.time.effects.TimeEffect" {
import {$TimeContext, $TimeContext$$Type} from "betterdays.time.TimeContext"

export interface $TimeEffect {

 "onTimeTick"(arg0: $TimeContext$$Type): void

(arg0: $TimeContext): void
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Literal": Special.BetterdaysTimeEffect
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Tag": Special.BetterdaysTimeEffectTag
}

export namespace $TimeEffect {
const probejs$$marker: never
}
export class $TimeEffect$$Static implements $TimeEffect {


 "onTimeTick"(arg0: $TimeContext$$Type): void
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $TimeEffect$$Type = (Special.BetterdaysTimeEffect) | ((arg0: $TimeContext) => void);
/**
 * Global type exported for convenience, use class-specific
 * types if there's a naming conflict.
 */
declare global {
export type $TimeEffect_ = $TimeEffect$$Type;
}}
declare module "betterdays.time.effects.PotionTimeEffect" {
import {$AbstractTimeEffect, $AbstractTimeEffect$$Type} from "betterdays.time.effects.AbstractTimeEffect"
import {$TimeContext, $TimeContext$$Type} from "betterdays.time.TimeContext"

export class $PotionTimeEffect extends $AbstractTimeEffect {

constructor()

public "onTimeTick"(arg0: $TimeContext$$Type): void
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $PotionTimeEffect$$Type = ($PotionTimeEffect);
/**
 * Global type exported for convenience, use class-specific
 * types if there's a naming conflict.
 */
declare global {
export type $PotionTimeEffect_ = $PotionTimeEffect$$Type;
}}
declare module "betterdays.time.Time" {
import {$Comparable, $Comparable$$Type} from "java.lang.Comparable"

export class $Time extends number implements $Comparable<($Time)> {
static readonly "DAY_TICKS": integer
static readonly "MORNING": $Time
static readonly "NOON": $Time
static readonly "DAY_LENGTH": $Time
static readonly "MIDNIGHT": $Time
static readonly "LUNAR_CYCLE_TICKS": integer
static readonly "LUNAR_CYCLE_LENGTH": $Time

constructor()
constructor(arg0: long, arg1: double)
constructor(arg0: double)
constructor(arg0: long)

public "negate"(): $Time
public "getDay"(): long
public "timeOfDay"(): $Time
public static "timeOfDay"(arg0: long): long
public "subtract"(arg0: long): $Time
public "subtract"(arg0: $Time$$Type): $Time
public "subtract"(arg0: double): $Time
public "divide"(arg0: double): double
public "divide"(arg0: long): double
public "divide"(arg0: $Time$$Type): double
public "equals"(arg0: any): boolean
public "toString"(): StringJS
public "hashCode"(): integer
public "abs"(): $Time
public "compareTo"(arg0: $Time$$Type): integer
public "compareTo"(arg0: any): integer
public "intValue"(): integer
public "longValue"(): long
public "floatValue"(): float
public "doubleValue"(): double
public "add"(arg0: double): $Time
public "add"(arg0: $Time$$Type): $Time
public "add"(arg0: long): $Time
public "mod"(arg0: long): $Time
public static "crossedMorning"(arg0: $Time$$Type, arg1: $Time$$Type): boolean
public "betweenMod"(arg0: $Time$$Type, arg1: $Time$$Type): boolean
public "fractionalValue"(): double
get "day"(): long
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Time$$Type = ($Time);
/**
 * Global type exported for convenience, use class-specific
 * types if there's a naming conflict.
 */
declare global {
export type $Time_ = $Time$$Type;
}}
declare module "betterdays.time.effects.WeatherSleepEffect" {
import {$AbstractTimeEffect, $AbstractTimeEffect$$Type} from "betterdays.time.effects.AbstractTimeEffect"
import {$TimeContext, $TimeContext$$Type} from "betterdays.time.TimeContext"

export class $WeatherSleepEffect extends $AbstractTimeEffect {

constructor()

public "onTimeTick"(arg0: $TimeContext$$Type): void
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $WeatherSleepEffect$$Type = ($WeatherSleepEffect);
/**
 * Global type exported for convenience, use class-specific
 * types if there's a naming conflict.
 */
declare global {
export type $WeatherSleepEffect_ = $WeatherSleepEffect$$Type;
}}
declare module "betterdays.time.effects.AbstractTimeEffect" {
import {$TimeContext, $TimeContext$$Type} from "betterdays.time.TimeContext"
import {$TimeEffect, $TimeEffect$$Type} from "betterdays.time.effects.TimeEffect"

export class $AbstractTimeEffect implements $TimeEffect {

constructor()

public "onTimeTick"(arg0: $TimeContext$$Type): void
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $AbstractTimeEffect$$Type = ($AbstractTimeEffect);
/**
 * Global type exported for convenience, use class-specific
 * types if there's a naming conflict.
 */
declare global {
export type $AbstractTimeEffect_ = $AbstractTimeEffect$$Type;
}}
declare module "betterdays.time.effects.HungerTimeEffect" {
import {$AbstractTimeEffect, $AbstractTimeEffect$$Type} from "betterdays.time.effects.AbstractTimeEffect"
import {$TimeContext, $TimeContext$$Type} from "betterdays.time.TimeContext"

export class $HungerTimeEffect extends $AbstractTimeEffect {

constructor()

public "onTimeTick"(arg0: $TimeContext$$Type): void
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $HungerTimeEffect$$Type = ($HungerTimeEffect);
/**
 * Global type exported for convenience, use class-specific
 * types if there's a naming conflict.
 */
declare global {
export type $HungerTimeEffect_ = $HungerTimeEffect$$Type;
}}
declare module "betterdays.time.TimeService" {
import {$SleepStatus, $SleepStatus$$Type} from "betterdays.time.SleepStatus"
import {$Time, $Time$$Type} from "betterdays.time.Time"
import {$ServerLevelWrapper, $ServerLevelWrapper$$Type} from "betterdays.wrappers.ServerLevelWrapper"

export class $TimeService {
readonly "sleepStatus": $SleepStatus
static readonly "NIGHT_START": $Time
readonly "level": $ServerLevelWrapper
static readonly "DAY_START": $Time

constructor(arg0: $ServerLevelWrapper$$Type)

public "tick"(): void
public "getDayTime"(): $Time
public "setDayTime"(arg0: $Time$$Type): $Time
public "getTimeSpeed"(arg0: $Time$$Type): double
public "broadcastTime"(): void
public "managesLevel"(arg0: $ServerLevelWrapper$$Type): boolean
get "dayTime"(): $Time
set "dayTime"(value: $Time$$Type)
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $TimeService$$Type = ($TimeService);
/**
 * Global type exported for convenience, use class-specific
 * types if there's a naming conflict.
 */
declare global {
export type $TimeService_ = $TimeService$$Type;
}}
declare module "betterdays.time.SleepStatus" {
import {$SleepStatus as $SleepStatus$0, $SleepStatus$$Type as $SleepStatus$0$$Type} from "net.minecraft.server.players.SleepStatus"
import {$Supplier, $Supplier$$Type} from "java.util.function.Supplier"
import {$List, $List$$Type} from "java.util.List"
import {$ServerPlayer, $ServerPlayer$$Type} from "net.minecraft.server.level.ServerPlayer"

export class $SleepStatus extends $SleepStatus$0 {

constructor(arg0: $Supplier$$Type<(boolean)>)

public "update"(arg0: $List$$Type<($ServerPlayer$$Type)>): boolean
public "ratio"(): double
public "amountSleeping"(): integer
public "sleepersNeeded"(arg0: integer): integer
public "percentage"(): integer
public "allAwake"(): boolean
public "areEnoughSleeping"(arg0: integer): boolean
public "areEnoughDeepSleeping"(arg0: integer, arg1: $List$$Type<($ServerPlayer$$Type)>): boolean
public "removeAllSleepers"(): void
public "amountActive"(): integer
public "updatePlayerCounts"(arg0: $List$$Type<($ServerPlayer$$Type)>): void
public "allAsleep"(): boolean
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $SleepStatus$$Type = ($SleepStatus);
/**
 * Global type exported for convenience, use class-specific
 * types if there's a naming conflict.
 */
declare global {
export type $SleepStatus_ = $SleepStatus$$Type;
}}
declare module "betterdays.time.TimeContext" {
import {$Time, $Time$$Type} from "betterdays.time.Time"
import {$TimeService, $TimeService$$Type} from "betterdays.time.TimeService"
import {$ServerLevelWrapper, $ServerLevelWrapper$$Type} from "betterdays.wrappers.ServerLevelWrapper"

export class $TimeContext {

constructor(arg0: $TimeService$$Type, arg1: $Time$$Type, arg2: $Time$$Type)

public "getLevel"(): $ServerLevelWrapper
public "getCurrentTime"(): $Time
public "getTimeService"(): $TimeService
public "getTimeDelta"(): $Time
get "level"(): $ServerLevelWrapper
get "currentTime"(): $Time
get "timeService"(): $TimeService
get "timeDelta"(): $Time
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $TimeContext$$Type = ($TimeContext);
/**
 * Global type exported for convenience, use class-specific
 * types if there's a naming conflict.
 */
declare global {
export type $TimeContext_ = $TimeContext$$Type;
}}
declare module "betterdays.time.effects.RandomTickSleepEffect" {
import {$AbstractTimeEffect, $AbstractTimeEffect$$Type} from "betterdays.time.effects.AbstractTimeEffect"
import {$TimeContext, $TimeContext$$Type} from "betterdays.time.TimeContext"

export class $RandomTickSleepEffect extends $AbstractTimeEffect {

constructor()

public "onTimeTick"(arg0: $TimeContext$$Type): void
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $RandomTickSleepEffect$$Type = ($RandomTickSleepEffect);
/**
 * Global type exported for convenience, use class-specific
 * types if there's a naming conflict.
 */
declare global {
export type $RandomTickSleepEffect_ = $RandomTickSleepEffect$$Type;
}}
declare module "betterdays.time.effects.BlockEntityTimeEffect" {
import {$AbstractTimeEffect, $AbstractTimeEffect$$Type} from "betterdays.time.effects.AbstractTimeEffect"
import {$TimeContext, $TimeContext$$Type} from "betterdays.time.TimeContext"

export class $BlockEntityTimeEffect extends $AbstractTimeEffect {

constructor()

public "onTimeTick"(arg0: $TimeContext$$Type): void
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $BlockEntityTimeEffect$$Type = ($BlockEntityTimeEffect);
/**
 * Global type exported for convenience, use class-specific
 * types if there's a naming conflict.
 */
declare global {
export type $BlockEntityTimeEffect_ = $BlockEntityTimeEffect$$Type;
}}
